### ISSUE TITLE
Temp files location and removal

### ISSUE THREAD

**Issue by anandksrao** [combogenomics/medusa#13]
I am trying to run medusa on my university HPC cluster and I receive some STDOUT messages that look like warnings / errors: (please see attached file with complete STDOUT)

[EthFoc173_Vs_6_MeDuSa-11374332.txt](https://github.com/combogenomics/medusa/files/900742/EthFoc173_Vs_6_MeDuSa-11374332.txt)

WARNING: there was a problem deleting the temporary output files

  File "medusa_scripts/netcon_mummer.py", line 5, in <module>
    import networkx as nx
ImportError: No module named networkx

And in the file nucmer.error created afresh, it reads:
20170405|132334|  6288| WARNING: there was a problem deleting the temporary output files

Could you please help me diagnose the list of things I need to fix on my compute cluster.
I've got this working this on my local machine, so I suspect some of this has to do with file / folder permissions. Yes?

Thanks!

**Comment by EBosi** [comment]
Hi,
you need to have networkx installed on your server. I don't know if you
have user-specific installation, you might better ask to a system
administrator about that, it should be really easy to do.
Let me know if you're OK with that fix.
Best,
Emanuele

**Comment by anandksrao** [comment]
My cluster admin says:
"networkx is already installed within the python module. Its possible the python module conflicts with other programs you are using."
Are there any specific runs and STDOUT / STDERR files I can share with you that might help you better diagnose my installation / use problem(s)? 
Thanks much!

**Comment by anandksrao** [comment]
Emanuele:
I am attaching STDOUT files for comparison of 1 target genomes Vs
2, 3, 4, 5, and 6 reference genomes, at a time.

Hopefully contents of these files help you diagnose errors quickly and easily - THANKS A LOT!

FYI: Only 1 run comparing Vs. 2 references was allowed to completion, other runs were manually terminated.




[EthFoc173_Vs_2_MeDuSa-11375460.TXT](https://github.com/combogenomics/medusa/files/918177/EthFoc173_Vs_2_MeDuSa-11375460.TXT)
[EthFoc173_Vs_3_MeDuSa-11375461.TXT](https://github.com/combogenomics/medusa/files/918178/EthFoc173_Vs_3_MeDuSa-11375461.TXT)
[EthFoc173_Vs_4_MeDuSa-11375462.TXT](https://github.com/combogenomics/medusa/files/918179/EthFoc173_Vs_4_MeDuSa-11375462.TXT)
[EthFoc173_Vs_5_MeDuSa-11375463.TXT](https://github.com/combogenomics/medusa/files/918180/EthFoc173_Vs_5_MeDuSa-11375463.TXT)
[EthFoc173_Vs_6_MeDuSa-11375464.TXT](https://github.com/combogenomics/medusa/files/918181/EthFoc173_Vs_6_MeDuSa-11375464.TXT)

**Comment by EBosi** [comment]
Hi, is this the same error as before?

Il 13 apr 2017 01:10, "anandksrao" <notifications@github.com> ha scritto:

**Comment by anandksrao** [comment]
Yeah, same error. our cluster was down for maintenance, no new runs since my 1st post on this thread, sorry was not clear.

**Comment by anandksrao** [comment]
Not sure if this will help rule out other errors, but here goes:

aksrao@farm:~$ which python
/usr/bin/python
aksrao@farm:~$ python --version
Python 2.7.6
aksrao@farm:~$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkx
>>> quit()
aksrao@farm:~$

**Comment by EBosi** [comment]
Give a shot to this one:
1) make a new account on the cluster and log in to it
2) install anaconda
3) conda install for the modules required by medusa
4) install medusa and other dependencies if needed
5) try running medusa with the test dataset

Let me know how that goes
Emanuele

**Comment by anandksrao** [comment]
I wonder if simultaneously running my shell scripts on a compute cluster, from the same folder location, for scaffolding of target genome "a" 
Vs (b,c) - 2 reference genomes
Vs (b,c,d) - 3 reference genomes
Vs (b,c,d,e) - 4 reference genomes
Vs (b,c,d,e,f) - 5 reference genomes
Vs (b,c,d,e,f,g) - 6 reference genomes
could be confusing the temp file generation and deletion process - so that cross-writing and cross-erasing of intermediate files could be messing up my runs? To test my hypothesis, I could simply run each of these within their folders, but before I kill these jobds, 1st I wanna know if this may be a problem at all.

For 1 target Vs 6 reference scaffolding (STDOUT attached), some of the worrisome lines read, as before - 
sh: 1: cannot open EthFoc-173_EthFoc-135_N50-filtered.mgaps: No such file
ERROR: postnuc returned non-zero
WARNING: there was a problem deleting the temporary output files
sh: 1: cannot open EthFoc-173_EthFoc-81_N50-filtered.mgaps: No such file
ERROR: postnuc returned non-zero
WARNING: there was a problem deleting the temporary output files

[EthFoc173_Vs_6_MeDuSa-11398161.txt](https://github.com/combogenomics/medusa/files/932172/EthFoc173_Vs_6_MeDuSa-11398161.txt)
Any suggestions?

**Comment by EBosi** [comment]
I would try running each instance in a separate folder, just to be sure

Il 19 apr 2017 08:58, "anandksrao" <notifications@github.com> ha scritto:

**Comment by anandksrao** [comment]
I can confidently confirm that using **individual folders for each run** was indeed the trick, and what I was missing in my previous runs.
