### ISSUE TITLE
No module named cPickle

### ISSUE THREAD

**Issue by fetyj** [combogenomics/medusa#14]
Hi,
I'm trying to run medus, but I'm stuck with error message during running test. I've attached a screenshot of the terminal, could you please help me to fix this issue?
![screenshot](https://cloud.githubusercontent.com/assets/13251325/24746043/1032e698-1ab8-11e7-93d2-607d3e218487.png)

Thanks!

**Comment by EBosi** [comment]
Hi,
thank you for using medusa. You should install cPickle python library. Give
it a try and tell me if that works.
Best,
Emanuele

**Comment by fetyj** [comment]
Hi,
It seems that in my version of python (3.6) the module is called _pickle so editing this line in the script (netcon_mummer.py) successfully worked.
Thanks for your help
Best
Fety

**Comment by EBosi** [comment]
Hi,
thank you for noticing that, I stick to python 2.7 so was unaware of the
change... anyway, I'm glad it works now, happy scaffolding!
Best
Ema
