### ISSUE TITLE
No edge weight in gexf output

### ISSUE THREAD

**Issue by ShaiberAlon** [combogenomics/medusa#16]
First, I want to thank you for developing this tool!

I have ran into the following issue while using your tool:
When using the -gexf option, I see that the edges don't have the weight information. Is there a way to save the full graph information including the weight of each edge?

Here is some information on what I did (in case this is my fault):

I used 106 reference genomes, and I ran the following command:
java -jar medusa.jar -f 01_FASTA/ -i myFASTA.fa -v -gexf -o myFASTA-medusa-fixed.fa

I'm running the following software version and dependencies:
Medusa version 1.6
Java version 1.8.0_101-b13
Biopython version 1.69
mummer version 3.0
Python version 2.7.13
networkx version 1.11

**Thank you very much!**

**Comment by EBosi** [comment]
Hi, thank you for using medusa, I'm glad you like it!
This is not a bug, it works as intended. I can work to add that feature (see issue #17 )
