### ISSUE TITLE
MUMmer version?

### ISSUE THREAD

**Issue by bibilujan** [combogenomics/medusa#21]
Hi, 

I want to use medusa to scaffold a (small) plant genome based on a close relative. I am getting a mummer error, is there a minimum version required? The system that I am working has "NUCmer (NUCleotide MUMmer) version 3.1". I do not have admin rights on this system, but I could install the newer version MUMmer locally. How can I tell medusa to use the local version instead? 

This is the error I encountered:

20171109|142440| 20204| ERROR: The following critical files could not be used
20171109|142440| 20204| /opt/bio/MUMmer/postnuc
20171109|142440| 20204| /opt/bio/MUMmer/prenuc
20171109|142440| 20204| Check your paths and file permissions and try again

Thank you,

Beatriz

**Comment by EBosi** [comment]
Hi Beatriz,
the version I'm working with is 3.1 as well so that should not be an
issue... have you tried using nucmer?
I suspect that your installed version is broken, if you want to check/fix
that you might want to open the nucmer script (for me is in
/usr/bin/nucmer) and check the content of the variable $AUX_BIN_DIR (right
at the beginning).

If you don't want to mess up with all of this and just install a local
version, I think it should work... if not I will write something quickly to
fix that!

Let me know how it goes.

Best,
Ema

**Comment by bibilujan** [comment]
Yes! it seems that nucmer is broken. I have a version of nucmer on my home already. I've been using this by just writing out the full path every time I run it. Is there a script in medusa that I can edit to indicate this path?  

Thank you for your time, 

Beatriz

**Comment by bibilujan** [comment]
I've edited the run mummer script and now I am getting a network error (python 2.7.3, networkx 1.1). 

INPUT FILE:test/Rhodobacter_target.fna
------------------------------------------------------------------------------------------------------------------------
Running MUMmer...1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "Rhodobacter_target_Rhodobacter_sphaeroides_WS8N.ntref" of length 4386797
# construct suffix tree for sequence of length 4386797
# (maximum reference length is 536870908)
# (maximum query length is 4294967295)
# process 43867 characters per dot
#....................................................................................................
# CONSTRUCTIONTIME /home/AAFC-AAC/lujantorob/Programs/MUMmer3.23/mummer Rhodobacter_target_Rhodobacter_sphaeroides_WS8N.ntref 1.38
# reading input file "/home/AAFC-AAC/lujantorob/Programs/medusa-master/test/reference_genomes/Rhodobacter_sphaeroides_WS8N.fna.inp" of length 4417791
# matching query-file "/home/AAFC-AAC/lujantorob/Programs/medusa-master/test/reference_genomes/Rhodobacter_sphaeroides_WS8N.fna.inp"
# against subject-file "Rhodobacter_target_Rhodobacter_sphaeroides_WS8N.ntref"
# COMPLETETIME /home/AAFC-AAC/lujantorob/Programs/MUMmer3.23/mummer Rhodobacter_target_Rhodobacter_sphaeroides_WS8N.ntref 4.71
# SPACE /home/AAFC-AAC/lujantorob/Programs/MUMmer3.23/mummer Rhodobacter_target_Rhodobacter_sphaeroides_WS8N.ntref 8.53
4: FINISHING DATA
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "Rhodobacter_target_Rhodobacter_SW2_uid40865.ntref" of length 4386797
# construct suffix tree for sequence of length 4386797
# (maximum reference length is 536870908)
# (maximum query length is 4294967295)
# process 43867 characters per dot
#....................................................................................................
# CONSTRUCTIONTIME /home/AAFC-AAC/lujantorob/Programs/MUMmer3.23/mummer Rhodobacter_target_Rhodobacter_SW2_uid40865.ntref 1.38
# reading input file "/home/AAFC-AAC/lujantorob/Programs/medusa-master/test/reference_genomes/Rhodobacter_SW2_uid40865.fna.inp" of length 3514400
# matching query-file "/home/AAFC-AAC/lujantorob/Programs/medusa-master/test/reference_genomes/Rhodobacter_SW2_uid40865.fna.inp"
# against subject-file "Rhodobacter_target_Rhodobacter_SW2_uid40865.ntref"
# COMPLETETIME /home/AAFC-AAC/lujantorob/Programs/MUMmer3.23/mummer Rhodobacter_target_Rhodobacter_SW2_uid40865.ntref 4.27
# SPACE /home/AAFC-AAC/lujantorob/Programs/MUMmer3.23/mummer Rhodobacter_target_Rhodobacter_SW2_uid40865.ntref 7.66
4: FINISHING DATA
done.
------------------------------------------------------------------------------------------------------------------------
Building the network...Traceback (most recent call last):
  File "medusa_scripts/netcon_mummer.py", line 260, in <module>
    if not testing: nx.write_gexf(G,out)
AttributeError: 'module' object has no attribute 'write_gexf'
Exception in thread "main" java.lang.RuntimeException: Error: Network construction failed.
	at Scaffolder.scaffolder(Unknown Source)
	at Scaffolder.runOnTerminal(Unknown Source)
	at Scaffolder.<init>(Unknown Source)
	at Scaffolder.main(Unknown Source)


Any thoughts, 

Beatriz

**Comment by EBosi** [comment]
Hi,
it looks like a networkx error... do you have it installed and which
version do you have?

**Comment by bibilujan** [comment]
Hi again, 

I have python 2.7.3 and networkx 1.1. 
(sorry for the giant letters on the prev. comment, I dont know why that happened)

Thanks, 
Beatriz

**Comment by bibilujan** [comment]
I had to update networkx and biopython (I did this through a python virtual environment), the test data worked! Now running my data. 
Thank you for your comments, 
Beatriz

**Comment by EBosi** [comment]
Glad it worked!
Happy scaffolding
Emanuele
