### ISSUE TITLE
Python 3.6 cPickle import issue on script

### ISSUE THREAD

**Issue by mberacochea** [combogenomics/medusa#23]
Thanks for the tool!

On python 3.6 the script `netcon_mummer.py` doesn't work because pickle has changed. Replacing the line `from cPickle import dump` to `from pickle import dump` fix the issue.

Regards

**Comment by oschwengers** [comment]
Following up on @mberacochea ...Would it be possible to update MeDuSa so it explicitly uses Python 3?
This would be a reasonable enhancement as Python 3.6 is already the default on Ubuntu 18.04 LTS.
