### ISSUE TITLE
Bio module import error

### ISSUE THREAD

**Issue by jananiharan** [combogenomics/medusa#27]
Hello, 

I get the following error when attempting to build scaffolds even when I have the latest version of Biopython installed:

> .....
> 
> # reading input file "/home/janani/NovelStreptomycesWGS.May18/new6T.draft.Apr18/6T.direct.assembly/ref.genomes/GCA_002192455.1_ASM219245v1_genomic.fna" of length 8144417
> # matching query-file "/home/janani/NovelStreptomycesWGS.May18/new6T.draft.Apr18/6T.direct.assembly/ref.genomes/GCA_002192455.1_ASM219245v1_genomic.fna"
> # against subject-file "6T_GCA_002192455.ntref"
> # COMPLETETIME /opt/anaconda2/opt/mummer-3.23/mummer 6T_GCA_002192455.ntref 10.45
> # SPACE /opt/anaconda2/opt/mummer-3.23/mummer 6T_GCA_002192455.ntref 16.41
> 4: FINISHING DATA
> done.
> 
> File "medusa_scripts/netcon_mummer.py", line 247, in <module>
>     G=initialize_graph(query_genome)
>   File "medusa_scripts/netcon_mummer.py", line 154, in initialize_graph
>     from Bio.SeqIO import parse
> ModuleNotFoundError: No module named 'Bio'
> Exception in thread "main" java.lang.RuntimeException: Error: Network construction failed.
> 	at Scaffolder.scaffolder(Unknown Source)
> 	at Scaffolder.runOnTerminal(Unknown Source)
> 	at Scaffolder.<init>(Unknown Source)
> 	at Scaffolder.main(Unknown Source)

Any suggestions on how to fix this error? Thanks!

**Comment by mgalardini** [comment]
Hi,

I believe you do not have the biopython module installed: you can do that by typing `python -m pip install biopython`, or refer to the [package's documentation](https://biopython.org/) for alternative solutions.

Hope this helps,
Marco
