### ISSUE TITLE
.inp file extension required on input fasta files ?`

### ISSUE THREAD

**Issue by colindaven** [combogenomics/medusa#3]
Hi,

this looks very interesting.

Is the .inp file ending required for the input fasta/s ? It seems that way from  the example and from my first attempts, but I didn't see this documented anywhere.

Thanks,
Colin

**Comment by mgalardini** [comment]
Hi,

no, the .inp extension is not required at the end of each target fasta file. The current version of Medusa expects the target files in a directory, which can be specified with the "-f" option.

From the README:

    java -jar medusa.jar -f test/reference_genomes/ -i test/Rhodobacter_target.fna -v

You then need to put your target fasta files in a directory (with no other files!) and then feed it into medusa by using the "-f" option.

Best,
Marco
