### ISSUE TITLE
Medusa error

### ISSUE THREAD

**Issue by kayobianco** [combogenomics/medusa#34]
hello everyone,

I installed medusa in an environment in conda, but I'm having difficulty using it. Can anyone help? 
best.

(medusa) kayobianco@ARQUEAS-XPS:~$ medusa -f /media/kayobianco/UBUNTU-HD/Illumina/Genomas/Neisseria_debora/N_meningitidis_CP021520 -i /media/kayobianco/UBUNTU-HD/Illumina/Genomas/Neisseria_debora/2779/unicycler_output/2779_assembly.fasta -o 2779_medusa_assembled -v
INPUT FILE:/media/kayobianco/UBUNTU-HD/Illumina/Genomas/Neisseria_debora/2779/unicycler_output/2779_assembly.fasta
------------------------------------------------------------------------------------------------------------------------
Running MUMmer.../home/kayobianco/miniconda3/envs/medusa/share/medusa-1.6-2/script//mummerRunner.sh: linha 11: nucmer: command not found
/home/kayobianco/miniconda3/envs/medusa/share/medusa-1.6-2/script//mummerRunner.sh: linha 12: show-coords: command not found
done.
------------------------------------------------------------------------------------------------------------------------
Building the network...Traceback (most recent call last):
  File "/home/kayobianco/miniconda3/envs/medusa/share/medusa-1.6-2/script//netcon_mummer.py", line 6, in <module>
    from cPickle import dump
ModuleNotFoundError: No module named 'cPickle'
Exception in thread "main" java.lang.RuntimeException: Error: Network construction failed.
	at Scaffolder.scaffolder(Unknown Source)
	at Scaffolder.runOnTerminal(Unknown Source)
	at Scaffolder.<init>(Unknown Source)
	at Scaffolder.main(Unknown Source)

**Comment by mgalardini** [comment]
Hi, is mummer installed in the conda environment you are using? You can check by typing `nucmer -h` in your terminal. If you get an error then run this after activating the environment: `conda install -c bioconda mummer4`.
