### ISSUE TITLE
textlen=812730787 larger than maximal textlen=536870908

### ISSUE THREAD

**Issue by macmanes** [combogenomics/medusa#6]
I am trying out medusa with a 900Mb genome. I think I am having issues with MUMmer - iI know not your software, but this may represent a hard limit in the genome size that one can scaffold. Please advise. 

This is using medusa code I cloned from GitHub today.

```
java -jar /share/medusa/medusa.jar -f ../assemblies/long/ -i ../assemblies/reference/asm.long.fa -o meduasa.fasta -v
INPUT FILE:../assemblies/reference/asm.long.fa
------------------------------------------------------------------------------------------------------------------------
Running MUMmer...1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "asm_AllPaths.ntref" of length 812730787
# construct suffix tree for sequence of length 812730787
# (maximum reference length is 536870908)
# (maximum query length is 4294967295)
# process 8127307 characters per dot
/usr/bin/mummer: suffix tree construction failed: textlen=812730787 larger than maximal textlen=536870908
ERROR: mummer and/or mgaps returned non-zero
ERROR: Could not parse delta file, asm_AllPaths.delta
error no: 400
```

**Comment by EBosi** [comment]
Dear Matt,
you need to install the 64bit version of mummer for large genomes. If you
need help I will be happy to support you.
Best,
Emanuele
Il 04/ago/2015 13:45 "Matt MacManes" <notifications@github.com> ha scritto:

**Comment by macmanes** [comment]
got it.. Never knew there was a 32bit limit by default in MUMmer.. This link was the key: https://sourceforge.net/p/mummer/discussion/451664/thread/59ad55aa/#bf1b

Might be worth a note in the README to this effect. I'm guessing most people will not know this.

Thanks.
