### ISSUE TITLE
w2 parameter explanation

### ISSUE THREAD

**Issue by habibr** [combogenomics/medusa#7]
In the program parameters' description, it says:

> The option -w2 is optional and allows for a sequence similarity based weighting scheme. Using a different weighting scheme may lead to better results.

I am a bit confused with the wordings. Which option would lead to better results? Turning -w2 on or off?

**Comment by mfondi** [comment]
Dear Habib,
thanks for your question. Indeed, the wording in the parameter's 
description could be misleading.
The sentence should read "Using a different weighting scheme may lead to 
better results than the default usage of MeDuSa"
Besides the approach describe in MeDuSa's paper, we have implemented a 
sequence-similarity based weighting scheme
that can be used to weight the edges of the scaffolding network (see 
additional material of the same paper). When we tested this approach on 
our dataset of genomes we found some improvements for some of them but 
not for all of them. So, you might want to try this option for your case 
and compare the results to the default usage of MeDuSa.

hope this helps.
cheers
m.



On 09/02/16 05:15, Habib R wrote:
>
> In the program parameters' description, it says:
>
>     The option -w2 is optional and allows for a sequence similarity
>     based weighting scheme. Using a different weighting scheme may
>     lead to better results.
>
> I am a bit confused with the wordings. Which option would lead to 
> better results? Turning -w2 on or off
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/combogenomics/medusa/issues/7>.
>


-- 
*******************
Marco Fondi, PhD
Dep. of Biology, University of Florence
Via Madonna del Piano 6, S. Fiorentino, Florence, Italy
Tel. +39 055 4574736
